# Generated by Django 4.2 on 2023-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('Department', models.CharField(max_length=200)),
                ('Post', models.CharField(max_length=200)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Zipcode', models.IntegerField()),
                ('State', models.CharField(max_length=200)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
    ]
