# Generated by Django 4.2 on 2023-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_rename_employee_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
