# Generated by Django 4.2 on 2023-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0003_alter_employees_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='leave_count',
            field=models.IntegerField(default=0),
        ),
    ]
